modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/5w14/auth-logic/issues"
license = "MIT"

[[mods]]
modId = "authlogic"
version = "${version}"
displayName = "AuthLogic"
authors = "5w14"
description = '''
Simple and effective authentication solution for modded servers.
'''
logoFile = "icon.png"

[[dependencies.authlogic]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.authlogic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.authlogic]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
